development:
  adapter: postgresql
  database: capstone_development
  encoding: unicode
  host: localhost
  pool: 15
  timeout: 5000

test:
  adapter: postgresql
  database: capstone_test
  encoding: unicode
  host: localhost
  pool: 15
  timeout: 5000

production:
  adapter: postgresql
  database: capstone_production
  encoding: unicode
  host: localhost
  pool: 15
  timeout: 5000
